name:  "\U0001F331 面试题投稿"
title: "【面试题】"
description: "感谢您抽出时间为 developer-plus 做贡献！"
body:
  - type: markdown
    attributes:
      value: |
        感谢您抽出时间为 developer-plus 做贡献！
  - type: textarea
    id: topic
    attributes:
      label: 题目
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: 答案
    validations:
      required: true
  - type: input
    id: type
    attributes:
      label: 类别
    validations:
      required: false
